### ISSUE TITLE
[issue] Instantianting an instrument block the main GUI

### ISSUE THREAD

**Issue by pyMatJ** [qcha41/usit#7]
When instantiating an instrument, the main GUI is not responsive. 
This can be annoying for some instruments that are long to instantiate (e.g. a laser that needs arming etc.).

Would it be possible to run the instantiation in a dedicated thread (maybe showing on the main GUI that something is happening using a color code/flashing/whatever) and update the GUI (with the QTreeWidgetItems) only after the init has finished ?

**Comment by Python-simulation** [comment]
Hi! I did it in commit [eb654f5](https://github.com/Python-simulation/autolab/commit/eb654f5b2ffa0adb7b9e1aa25b7467b5fc205cad) if you are still looking for a solution.
